
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_sandbox_cert'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
#analysis-paths: ["analyses"]
#test-paths: ["tests"]
seed-paths: ["seeds"]
#macro-paths: ["macros"]
#snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


on-run-start:
  - "{% do run_query('CREATE SCHEMA IF NOT EXISTS `'
        ~ target.project ~ '`.bronze') %}"
  - "{% do run_query('CREATE TABLE IF NOT EXISTS `'
        ~ target.project ~ '`.bronze.raw_workout_data (\
          workout_id STRING,\
          workout_timestamp TIMESTAMP,\
          length_minutes INT64,\
          class_title STRING,\
          total_output FLOAT64,\
          avg_watts FLOAT64,\
          distance_km FLOAT64,\
          calories_burned INT64,\
          avg_heartrate_bpm INT64,\
          fitness_discipline STRING,\
          instructor STRING)') %}"
  - "{% do run_query('INSERT INTO `'
        ~ target.project ~ '`.bronze.raw_workout_data \
          (workout_id, workout_timestamp, length_minutes, class_title, total_output, avg_watts, distance_km, calories_burned, avg_heartrate_bpm, fitness_discipline, instructor) VALUES \
          (\\'w1\\', TIMESTAMP(\\'2025-10-01 09:00:00+00\\'), 30, \\'HIIT Ride\\', 320.5, 210.0, 14.2, 350, 145, \\'Cycling\\', \\'Alex T\\'), \
          (\\'w2\\', TIMESTAMP(\\'2025-10-02 18:30:00+00\\'), 45, \\'Endurance Run\\', 500.0, 185.0, 8.5, 520, 152, \\'Treadmill\\', \\'Jess S\\'), \
          (\\'w3\\', TIMESTAMP(\\'2025-10-03 07:15:00+00\\'), 20, \\'Yoga Flow\\', 120.0, NULL, 0.0, 80, 98, \\'Yoga\\', \\'Aditi S\\')') %}"



# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
# The configuration below will override this setting for models in the example folder to 
# instead be materialized as tables. Any models you add to the root of the models folder will 
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  dbt_sandbox_cert:
    bronze:
    +schema: bronze
  
seeds:
  dbt_sandbox_cert:
    +schema: reference
    +quote_columns: false
    fitness_discipline:
      +schema: reference
      +column_types:
        fitness_discipline: string
        is_active: boolean 
    fitness_type_seed:
      +schema: reference
      +column_types:
        fitness_type: string
        is_active: boolean 