# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_sandbox_cert'
version: '1.0.0'
config-version: 2

# Can define a target path where artifacts location can be chosen
target-path: "target"  # set it as the default

# var overrides
vars:
  surrogate_key_treat_nulls_as_empty_strings: true

# This setting makes sure that only 'public' models will be exposed or referencable to other projects
#restrict-access: true

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
#analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
docs-paths: ["docs"]
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

on-run-start:
  - "{% do run_query('CREATE SCHEMA IF NOT EXISTS `' ~ target.project ~ '`.audit') %}"
  - "{% do run_query('CREATE TABLE IF NOT EXISTS `' ~ target.project ~ '`.audit.run_log (invocation_id STRING, started_at TIMESTAMP, ended_at TIMESTAMP, user STRING, status STRING)') %}"
  - "{% do run_query('INSERT INTO `' ~ target.project ~ '`.audit.run_log (invocation_id, started_at, ended_at, user, status) ' ~ 'VALUES (\\'' ~ invocation_id ~ '\\', CURRENT_TIMESTAMP(), NULL, SESSION_USER(), \\'' ~ 'running' ~ '\\')') %}"

on-run-end:
  - "{% do run_query('UPDATE `' ~ target.project ~ '`.audit.run_log SET ended_at = CURRENT_TIMESTAMP(), status = \\'' ~ 'finished' ~ '\\' ' ~ 'WHERE invocation_id = \\'' ~ invocation_id ~ '\\'') %}"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
# The configuration below will override this setting for models in the example folder to 
# instead be materialized as tables. Any models you add to the root of the models folder will 
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  dbt_sandbox_cert:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +schema: staging
    intermediate:
      +schema: intermediate
    marts:
      +schema: marts

seeds:
  +persist_docs:
    relation: true
    columns: true
  dbt_sandbox_cert:
    +schema: reference
    +quote_columns: false
    fitness_disciplines:
      +column_types:
        fitness_discipline: string
        is_active: boolean
    fitness_types:
      +column_types:
        fitness_type: string
        is_active: boolean
    test_customers:
      +enabled: "{{ target.name == 'dev' }}" 
      +column_types:
        username: string
        is_active: boolean


tests:
  dbt_sandbox_cert:
    +store_failures: true
    +schema: tests
flags:
  require_generic_test_arguments_property: true

